# Generated by Django 5.2.9 on 2026-06-05 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrance_cam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='Webcam index (0, 1, …) or IP stream URL e.g. http://192.168.1.100:8080/video', max_length=300)),
                ('location', models.CharField(default='Entrance', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CameraAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('entry_emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('surprise', 'Surprise'), ('fear', 'Fear'), ('disgust', 'Disgust'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('exit_emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('surprise', 'Surprise'), ('fear', 'Fear'), ('disgust', 'Disgust'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('entry_emotion_score', models.FloatField(default=0.0)),
                ('exit_emotion_score', models.FloatField(default=0.0)),
                ('entry_snapshot', models.ImageField(blank=True, null=True, upload_to='camera/entry/')),
                ('exit_snapshot', models.ImageField(blank=True, null=True, upload_to='camera/exit/')),
                ('mood_comparison', models.CharField(blank=True, choices=[('improved', 'Improved'), ('declined', 'Declined'), ('stable', 'Stable'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_attendance_logs', to='camera_attendance.camera')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_attendance_logs', to='entrance_cam.student')),
            ],
            options={
                'verbose_name': 'Camera Attendance Log',
                'verbose_name_plural': 'Camera Attendance Logs',
                'ordering': ['-date', '-entry_time'],
                'indexes': [models.Index(fields=['student', 'date'], name='camera_atte_student_afc153_idx'), models.Index(fields=['date', '-entry_time'], name='camera_atte_date_143547_idx')],
            },
        ),
    ]
