# Generated by Django 5.2.9 on 2026-06-01 16:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_attendance', '0001_initial'),
        ('entrance_cam', '0009_alter_attendancelog_options_alter_camera_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraattendancelog',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_attendance_logs', to='entrance_cam.camera'),
        ),
        migrations.AlterField(
            model_name='cameraattendancelog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
