[program:gunicorn]
command=gunicorn --workers 4 --worker-class gthread --threads 8 --timeout 0 --bind 0.0.0.0:8000 classroom_iot.wsgi:application
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/gunicorn.log
priority=999