# Generated by Django 6.0.5 on 2026-05-15 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='IP camera stream URL e.g. http://192.168.1.100:8080/video', max_length=300)),
                ('location', models.CharField(default='Entrance', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('B.Sc', 'B.Sc'), ('M.Sc', 'M.Sc'), ('MBA', 'MBA'), ('Other', 'Other')], max_length=20)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')])),
                ('photo', models.ImageField(upload_to='students/photos/')),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('entry_emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('surprise', 'Surprise'), ('fear', 'Fear'), ('disgust', 'Disgust'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('exit_emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('surprise', 'Surprise'), ('fear', 'Fear'), ('disgust', 'Disgust'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('entry_emotion_score', models.FloatField(default=0.0)),
                ('exit_emotion_score', models.FloatField(default=0.0)),
                ('entry_snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/entry/')),
                ('exit_snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/exit/')),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrance_cam.camera')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='entrance_cam.student')),
            ],
            options={
                'ordering': ['-date', '-entry_time'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
