# Generated by Django 5.2.9 on 2026-06-04 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='Webcam index (0, 1, …) or IP stream URL e.g. http://192.168.1.100:8080/video', max_length=300)),
                ('location', models.CharField(default='Entrance', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('B.Sc', 'B.Sc'), ('M.Sc', 'M.Sc'), ('MBA', 'MBA'), ('Other', 'Other')], max_length=20)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')])),
                ('photo', models.ImageField(upload_to='students/photos/')),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('fingerprint_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('is_enrolled', models.BooleanField(default=False, help_text='True if face encoding generated successfully (for camera detection)')),
                ('fp_confidence', models.IntegerField(blank=True, null=True)),
                ('fp_scan_count', models.IntegerField(default=0)),
                ('fp_last_seen', models.DateTimeField(blank=True, null=True)),
                ('fp_image', models.ImageField(blank=True, null=True, upload_to='fingerprints/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ESP32Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(help_text='ESP32 IP address or server URL', max_length=100)),
                ('location', models.CharField(default='Main Entrance', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('enrollment_mode', models.BooleanField(default=False)),
                ('pending_fingerprint_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_device', to='entrance_cam.student')),
            ],
            options={
                'verbose_name': 'ESP32 Device',
                'verbose_name_plural': 'ESP32 Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FingerprintAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], default='entry', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('fingerprint_id', models.IntegerField()),
                ('confidence', models.IntegerField(default=0, help_text='Fingerprint match confidence (0-255)')),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='entrance_cam.esp32device')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_attendance_logs', to='entrance_cam.student')),
            ],
            options={
                'verbose_name': 'Fingerprint Attendance',
                'verbose_name_plural': 'Fingerprint Attendance Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', 'date'], name='entrance_ca_student_4af89f_idx'), models.Index(fields=['timestamp'], name='entrance_ca_timesta_3768e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('entry_emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('surprise', 'Surprise'), ('fear', 'Fear'), ('disgust', 'Disgust'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('exit_emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('surprise', 'Surprise'), ('fear', 'Fear'), ('disgust', 'Disgust'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('entry_emotion_score', models.FloatField(default=0.0)),
                ('exit_emotion_score', models.FloatField(default=0.0)),
                ('entry_snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/entry/')),
                ('exit_snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/exit/')),
                ('mood_comparison', models.CharField(blank=True, choices=[('improved', 'Improved'), ('declined', 'Declined'), ('stable', 'Stable'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrance_cam.camera')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='entrance_cam.student')),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'ordering': ['-date', '-entry_time'],
                'indexes': [models.Index(fields=['student', 'date'], name='entrance_ca_student_ff351c_idx'), models.Index(fields=['date', '-entry_time'], name='entrance_ca_date_4ef60a_idx'), models.Index(fields=['camera', 'date'], name='entrance_ca_camera__569558_idx')],
            },
        ),
    ]
