# Generated by Django 5.2.9 on 2026-05-21 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance_cam', '0002_student_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='mood_comparison',
            field=models.CharField(blank=True, choices=[('improved', 'Improved'), ('declined', 'Declined'), ('stable', 'Stable'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
