# Generated by Django 5.2.14 on 2026-05-30 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance_cam', '0003_alter_attendancelog_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('phone_usage', 'Phone Usage'), ('eating_food', 'Eating Food'), ('fighting', 'Fighting/Altercation'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='incidents/')),
                ('confidence', models.FloatField(default=0.0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrance_cam.camera')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reviews', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='entrance_cam.student')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['student', '-detected_at'], name='entrance_ca_student_359160_idx'), models.Index(fields=['incident_type', '-detected_at'], name='entrance_ca_inciden_512721_idx'), models.Index(fields=['whatsapp_sent', 'detected_at'], name='entrance_ca_whatsap_97cc7d_idx')],
            },
        ),
    ]
