# Generated by Django 5.2.14 on 2026-05-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance_cam', '0004_incidentreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncidentReport',
        ),
    ]
