# Generated by Django 5.2.14 on 2026-05-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance_cam', '0005_delete_incidentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.CharField(help_text='Webcam index (0, 1, …) or IP stream URL e.g. http://192.168.1.100:8080/video', max_length=300),
        ),
    ]
