# Generated by Django 5.2.9 on 2026-05-31 13:48

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance_cam', '0006_alter_camera_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fingerprint_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fp_confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fp_image',
            field=models.ImageField(blank=True, null=True, upload_to='fingerprints/'),
        ),
        migrations.AddField(
            model_name='student',
            name='fp_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fp_scan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ESP32Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(help_text='ESP32 IP address or server URL', max_length=100)),
                ('location', models.CharField(default='Main Entrance', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('enrollment_mode', models.BooleanField(default=False)),
                ('pending_fingerprint_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_device', to='entrance_cam.student')),
            ],
            options={
                'verbose_name': 'ESP32 Device',
                'verbose_name_plural': 'ESP32 Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FingerprintAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], default='entry', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=datetime.date.today)),
                ('fingerprint_id', models.IntegerField()),
                ('confidence', models.IntegerField(default=0, help_text='Fingerprint match confidence (0-255)')),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='entrance_cam.esp32device')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_attendance_logs', to='entrance_cam.student')),
            ],
            options={
                'verbose_name': 'Fingerprint Attendance',
                'verbose_name_plural': 'Fingerprint Attendance Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', 'date'], name='entrance_ca_student_4af89f_idx'), models.Index(fields=['timestamp'], name='entrance_ca_timesta_3768e7_idx')],
            },
        ),
    ]
