# Generated by Django 5.2.9 on 2026-06-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance_cam', '0007_student_fingerprint_id_student_fp_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_enrolled',
            field=models.BooleanField(default=False, help_text='True if face encoding generated successfully (for camera detection)'),
        ),
    ]
