# Generated by Django 5.2.9 on 2026-06-01 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance_cam', '0008_alter_student_is_enrolled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancelog',
            options={'ordering': ['-date', '-entry_time'], 'verbose_name': 'Attendance Log', 'verbose_name_plural': 'Attendance Logs'},
        ),
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['name'], 'verbose_name': 'Camera', 'verbose_name_plural': 'Cameras'},
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fingerprintattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['student', 'date'], name='entrance_ca_student_ff351c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['date', '-entry_time'], name='entrance_ca_date_4ef60a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['camera', 'date'], name='entrance_ca_camera__569558_idx'),
        ),
    ]
