# Generated by Django 5.2.9 on 2026-05-16 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrance_cam', '0002_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions', to='entrance_cam.student')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CameraSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lab/camera/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('surprise', 'Surprise'), ('fear', 'Fear'), ('disgust', 'Disgust'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('emotion_score', models.FloatField(default=0.0)),
                ('pose', models.CharField(choices=[('focused', 'Focused'), ('looking_away', 'Looking Away'), ('head_down', 'Head Down'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_snapshots', to='lab_monitor.labsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tab_title', models.CharField(blank=True, max_length=300)),
                ('activity_type', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('tab_change', 'Tab Change')], default='active', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='lab_monitor.labsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lab/screenshots/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tab_title', models.CharField(blank=True, max_length=300)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='lab_monitor.labsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
