# Generated by Django 5.2.14 on 2026-05-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsession',
            name='webrtc_answer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsession',
            name='webrtc_ice_candidates_admin',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='labsession',
            name='webrtc_ice_candidates_student',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='labsession',
            name='webrtc_offer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
