# Generated by Django 5.2.14 on 2026-05-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_monitor', '0002_labsession_webrtc_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsession',
            name='webrtc_camera_stream_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labsession',
            name='webrtc_screen_stream_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
