# Generated by Django 5.2.9 on 2026-06-04 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrance_cam', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='RTSP or HTTP stream URL', max_length=300)),
                ('location', models.CharField(default='Classroom', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('stream_type', models.CharField(choices=[('mjpeg', 'MJPEG'), ('rtsp', 'RTSP'), ('snapshot', 'Snapshot')], default='mjpeg', max_length=10)),
                ('snapshot_url', models.CharField(blank=True, help_text='Direct snapshot URL if different from stream URL', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Classroom Camera',
                'verbose_name_plural': 'Classroom Cameras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(help_text='Upload MP4 or AVI video', upload_to='classroom/videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('total_frames_analyzed', models.IntegerField(default=0)),
                ('total_students_detected', models.IntegerField(default=0)),
                ('average_engagement_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this video')),
            ],
            options={
                'verbose_name': 'Classroom Video',
                'verbose_name_plural': 'Classroom Videos',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['status', '-uploaded_at'], name='classroom_m_status_3e0ec3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('teacher', models.CharField(blank=True, max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_students_detected', models.IntegerField(default=0)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom_monitor.classroomcamera')),
            ],
            options={
                'verbose_name': 'Class Session',
                'verbose_name_plural': 'Class Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EngagementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frame_image', models.ImageField(blank=True, null=True, upload_to='classroom/frames/')),
                ('focused_count', models.IntegerField(default=0)),
                ('looking_away_count', models.IntegerField(default=0)),
                ('head_down_count', models.IntegerField(default=0)),
                ('using_phone_count', models.IntegerField(default=0)),
                ('eating_count', models.IntegerField(default=0)),
                ('not_visible_count', models.IntegerField(default=0)),
                ('talking_count', models.IntegerField(default=0)),
                ('total_detected', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='classroom_monitor.classsession')),
            ],
            options={
                'verbose_name': 'Engagement Snapshot',
                'verbose_name_plural': 'Engagement Snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('fighting', 'Physical Fight'), ('using_phone', 'Using Phone'), ('eating_food', 'Eating Food'), ('looking_away', 'Looking Away'), ('head_down', 'Head Down'), ('distracted', 'Distracted'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='incidents/')),
                ('confidence', models.FloatField(default=0.0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrance_cam.camera')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reviews', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='entrance_cam.student')),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentZoneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField()),
                ('pose', models.CharField(choices=[('focused', 'Focused'), ('looking_away', 'Looking Away'), ('head_down', 'Head Down'), ('using_phone', 'Using Phone'), ('eating', 'Eating'), ('not_visible', 'Not Visible')], default='not_visible', max_length=20)),
                ('possibly_talking', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_logs', to='classroom_monitor.engagementsnapshot')),
            ],
            options={
                'verbose_name': 'Student Zone Log',
                'verbose_name_plural': 'Student Zone Logs',
                'ordering': ['snapshot', 'zone_id'],
            },
        ),
        migrations.CreateModel(
            name='VideoAnalysisFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('timestamp', models.FloatField()),
                ('frame_image', models.ImageField(blank=True, null=True, upload_to='classroom/video_frames/')),
                ('focused_count', models.IntegerField(default=0)),
                ('looking_away_count', models.IntegerField(default=0)),
                ('head_down_count', models.IntegerField(default=0)),
                ('using_phone_count', models.IntegerField(default=0)),
                ('eating_count', models.IntegerField(default=0)),
                ('not_visible_count', models.IntegerField(default=0)),
                ('total_detected', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='classroom_monitor.classroomvideo')),
            ],
            options={
                'verbose_name': 'Video Analysis Frame',
                'verbose_name_plural': 'Video Analysis Frames',
                'ordering': ['frame_number'],
            },
        ),
        migrations.CreateModel(
            name='VideoStudentZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField()),
                ('pose', models.CharField(choices=[('focused', 'Focused'), ('looking_away', 'Looking Away'), ('head_down', 'Head Down'), ('using_phone', 'Using Phone'), ('eating', 'Eating'), ('not_visible', 'Not Visible')], default='not_visible', max_length=20)),
                ('possibly_talking', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='classroom_monitor.videoanalysisframe')),
            ],
            options={
                'verbose_name': 'Video Student Zone',
                'verbose_name_plural': 'Video Student Zones',
                'ordering': ['frame', 'zone_id'],
            },
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['camera', '-start_time'], name='classroom_m_camera__330493_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['is_active', '-start_time'], name='classroom_m_is_acti_45b707_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementsnapshot',
            index=models.Index(fields=['session', '-timestamp'], name='classroom_m_session_83381d_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementsnapshot',
            index=models.Index(fields=['timestamp'], name='classroom_m_timesta_000277_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['student', '-detected_at'], name='classroom_m_student_d2858a_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['incident_type', '-detected_at'], name='classroom_m_inciden_0dc79b_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['severity', '-detected_at'], name='classroom_m_severit_deb6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentzonelog',
            index=models.Index(fields=['snapshot', 'zone_id'], name='classroom_m_snapsho_7f6b48_idx'),
        ),
        migrations.AddIndex(
            model_name='videoanalysisframe',
            index=models.Index(fields=['video', 'frame_number'], name='classroom_m_video_i_a0b435_idx'),
        ),
        migrations.AddIndex(
            model_name='videoanalysisframe',
            index=models.Index(fields=['timestamp'], name='classroom_m_timesta_d0016d_idx'),
        ),
        migrations.AddIndex(
            model_name='videostudentzone',
            index=models.Index(fields=['frame', 'zone_id'], name='classroom_m_frame_i_671c44_idx'),
        ),
    ]
