# Generated by Django 5.2.9 on 2026-05-19 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='RTSP or HTTP stream URL', max_length=300)),
                ('location', models.CharField(default='Classroom', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('stream_type', models.CharField(choices=[('mjpeg', 'MJPEG'), ('rtsp', 'RTSP'), ('snapshot', 'Snapshot')], default='mjpeg', max_length=10)),
                ('snapshot_url', models.CharField(blank=True, help_text='Direct snapshot URL if different from stream URL', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('teacher', models.CharField(blank=True, max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_students_detected', models.IntegerField(default=0)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom_monitor.classroomcamera')),
            ],
        ),
        migrations.CreateModel(
            name='EngagementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frame_image', models.ImageField(blank=True, null=True, upload_to='classroom/frames/')),
                ('focused_count', models.IntegerField(default=0)),
                ('looking_away_count', models.IntegerField(default=0)),
                ('head_down_count', models.IntegerField(default=0)),
                ('not_visible_count', models.IntegerField(default=0)),
                ('talking_count', models.IntegerField(default=0)),
                ('total_detected', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='classroom_monitor.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='StudentZoneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField()),
                ('pose', models.CharField(choices=[('focused', 'Focused'), ('looking_away', 'Looking Away'), ('head_down', 'Head Down'), ('not_visible', 'Not Visible')], default='not_visible', max_length=20)),
                ('possibly_talking', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_logs', to='classroom_monitor.engagementsnapshot')),
            ],
        ),
    ]
