# Generated by Django 5.2.9 on 2026-05-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(help_text='Upload MP4 or AVI video', upload_to='classroom/videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('total_frames_analyzed', models.IntegerField(default=0)),
                ('total_students_detected', models.IntegerField(default=0)),
                ('average_engagement_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAnalysisFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('timestamp', models.FloatField()),
                ('frame_image', models.ImageField(blank=True, null=True, upload_to='classroom/video_frames/')),
                ('focused_count', models.IntegerField(default=0)),
                ('looking_away_count', models.IntegerField(default=0)),
                ('head_down_count', models.IntegerField(default=0)),
                ('not_visible_count', models.IntegerField(default=0)),
                ('total_detected', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='classroom_monitor.classroomvideo')),
            ],
            options={
                'ordering': ['frame_number'],
            },
        ),
        migrations.CreateModel(
            name='VideoStudentZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField()),
                ('pose', models.CharField(choices=[('focused', 'Focused'), ('looking_away', 'Looking Away'), ('head_down', 'Head Down'), ('not_visible', 'Not Visible')], default='not_visible', max_length=20)),
                ('possibly_talking', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='classroom_monitor.videoanalysisframe')),
            ],
        ),
    ]
