# Generated by Django 5.2.9 on 2026-05-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_monitor', '0002_classroomvideo_videoanalysisframe_videostudentzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementsnapshot',
            name='eating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engagementsnapshot',
            name='fighting_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engagementsnapshot',
            name='using_phone_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoanalysisframe',
            name='eating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoanalysisframe',
            name='fighting_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoanalysisframe',
            name='using_phone_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentzonelog',
            name='pose',
            field=models.CharField(choices=[('focused', 'Focused'), ('looking_away', 'Looking Away'), ('head_down', 'Head Down'), ('using_phone', 'Using Phone'), ('eating', 'Eating'), ('fighting', 'Fighting'), ('not_visible', 'Not Visible')], default='not_visible', max_length=20),
        ),
        migrations.AlterField(
            model_name='videostudentzone',
            name='pose',
            field=models.CharField(choices=[('focused', 'Focused'), ('looking_away', 'Looking Away'), ('head_down', 'Head Down'), ('using_phone', 'Using Phone'), ('eating', 'Eating'), ('fighting', 'Fighting'), ('not_visible', 'Not Visible')], default='not_visible', max_length=20),
        ),
    ]
