# Generated by Django 5.2.9 on 2026-06-01 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_monitor', '0005_remove_fighting_count'),
        ('entrance_cam', '0009_alter_attendancelog_options_alter_camera_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomcamera',
            options={'ordering': ['name'], 'verbose_name': 'Classroom Camera', 'verbose_name_plural': 'Classroom Cameras'},
        ),
        migrations.AlterModelOptions(
            name='classroomvideo',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Classroom Video', 'verbose_name_plural': 'Classroom Videos'},
        ),
        migrations.AlterModelOptions(
            name='classsession',
            options={'ordering': ['-start_time'], 'verbose_name': 'Class Session', 'verbose_name_plural': 'Class Sessions'},
        ),
        migrations.AlterModelOptions(
            name='engagementsnapshot',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Engagement Snapshot', 'verbose_name_plural': 'Engagement Snapshots'},
        ),
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'ordering': ['-detected_at'], 'verbose_name': 'Incident Report', 'verbose_name_plural': 'Incident Reports'},
        ),
        migrations.AlterModelOptions(
            name='studentzonelog',
            options={'ordering': ['snapshot', 'zone_id'], 'verbose_name': 'Student Zone Log', 'verbose_name_plural': 'Student Zone Logs'},
        ),
        migrations.AlterModelOptions(
            name='videoanalysisframe',
            options={'ordering': ['frame_number'], 'verbose_name': 'Video Analysis Frame', 'verbose_name_plural': 'Video Analysis Frames'},
        ),
        migrations.AlterModelOptions(
            name='videostudentzone',
            options={'ordering': ['frame', 'zone_id'], 'verbose_name': 'Video Student Zone', 'verbose_name_plural': 'Video Student Zones'},
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_type',
            field=models.CharField(choices=[('using_phone', 'Using Phone'), ('eating_food', 'Eating Food'), ('looking_away', 'Looking Away'), ('head_down', 'Head Down'), ('distracted', 'Distracted'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentzonelog',
            name='pose',
            field=models.CharField(choices=[('focused', 'Focused'), ('looking_away', 'Looking Away'), ('head_down', 'Head Down'), ('using_phone', 'Using Phone'), ('eating', 'Eating'), ('not_visible', 'Not Visible')], default='not_visible', max_length=20),
        ),
        migrations.AlterField(
            model_name='videostudentzone',
            name='pose',
            field=models.CharField(choices=[('focused', 'Focused'), ('looking_away', 'Looking Away'), ('head_down', 'Head Down'), ('using_phone', 'Using Phone'), ('eating', 'Eating'), ('not_visible', 'Not Visible')], default='not_visible', max_length=20),
        ),
        migrations.AddIndex(
            model_name='classroomvideo',
            index=models.Index(fields=['status', '-uploaded_at'], name='classroom_m_status_3e0ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['camera', '-start_time'], name='classroom_m_camera__330493_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['is_active', '-start_time'], name='classroom_m_is_acti_45b707_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementsnapshot',
            index=models.Index(fields=['session', '-timestamp'], name='classroom_m_session_83381d_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementsnapshot',
            index=models.Index(fields=['timestamp'], name='classroom_m_timesta_000277_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['severity', '-detected_at'], name='classroom_m_severit_deb6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentzonelog',
            index=models.Index(fields=['snapshot', 'zone_id'], name='classroom_m_snapsho_7f6b48_idx'),
        ),
        migrations.AddIndex(
            model_name='videoanalysisframe',
            index=models.Index(fields=['video', 'frame_number'], name='classroom_m_video_i_a0b435_idx'),
        ),
        migrations.AddIndex(
            model_name='videoanalysisframe',
            index=models.Index(fields=['timestamp'], name='classroom_m_timesta_d0016d_idx'),
        ),
        migrations.AddIndex(
            model_name='videostudentzone',
            index=models.Index(fields=['frame', 'zone_id'], name='classroom_m_frame_i_671c44_idx'),
        ),
    ]
